_wandb:
    value:
        cli_version: 0.23.0
        e:
            r3nwu8uyf9h30z1bie3lmi9wrmb4jamb:
                codePath: train_sae.py
                codePathLocal: train_sae.py
                cpu_count: 128
                cpu_count_logical: 128
                disk:
                    /:
                        total: "119966646272"
                        used: "20247977984"
                email: akaur64@asu.edu
                executable: /home/akaur64/mambaenvs/py312/bin/python
                host: sc080
                memory:
                    total: "540601946112"
                os: Linux-4.18.0-553.124.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /home/akaur64/train_SAE/train_sae.py
                python: CPython 3.12.13
                root: /home/akaur64/train_SAE
                slurm:
                    cluster_name: sol
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "1"
                    cpus_per_task: "1"
                    gtids: "0"
                    job_account: grp_hkerner
                    job_cpus_per_node: "1"
                    job_end_time: "1783649167"
                    job_gid: "99999810"
                    job_group: grp_hkerner
                    job_id: "58830518"
                    job_name: interactive
                    job_nodelist: sc080
                    job_num_nodes: "1"
                    job_partition: htc
                    job_qos: public
                    job_start_time: "1783643767"
                    job_uid: "3118458"
                    job_user: akaur64
                    jobid: "58830518"
                    launch_node_ipaddr: 10.139.120.43
                    localid: "0"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: sc080
                    oom_kill_step: "0"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "46883"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "35949"
                    pty_win_col: "77"
                    pty_win_row: "13"
                    script_context: prolog_task
                    srun_comm_host: 10.139.120.43
                    srun_comm_port: "42663"
                    step_id: "4294967290"
                    step_launcher_port: "42663"
                    step_nodelist: sc080
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /home/akaur64/train_SAE
                    submit_host: sol-login04
                    task_pid: "1425103"
                    tasks_per_node: "1"
                    topology_addr: sc080
                    topology_addr_pattern: node
                    tres_per_task: cpu=1
                startedAt: "2026-07-10T00:42:20.700981Z"
                writerId: r3nwu8uyf9h30z1bie3lmi9wrmb4jamb
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 105
            "3":
                - 16
            "4": 3.12.13
            "5": 0.23.0
            "6": 5.12.1
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 256
d_in:
    value: 192
d_sae:
    value: 1536
device:
    value: cpu
epochs:
    value: 20
expansion_factor:
    value: 8
l1:
    value: 0.0001
lr:
    value: 0.001
