_wandb:
    value:
        cli_version: 0.23.0
        e:
            7vx69ew96cq0vbpgetbb53ze7ngzppg1:
                codePath: train_sae.py
                codePathLocal: train_sae.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "137369751552"
                        used: "57288818688"
                email: akaur64@asu.edu
                executable: /home/akaur64/mambaenvs/py312/bin/python
                host: sol-login04
                memory:
                    total: "33700929536"
                os: Linux-4.18.0-553.124.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /home/akaur64/train_SAE/train_sae.py
                python: CPython 3.12.13
                root: /home/akaur64/train_SAE
                startedAt: "2026-07-14T05:08:46.074413Z"
                writerId: 7vx69ew96cq0vbpgetbb53ze7ngzppg1
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 105
            "3":
                - 16
            "4": 3.12.13
            "5": 0.23.0
            "6": 5.12.1
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 256
d_in:
    value: 192
d_sae:
    value: 1536
device:
    value: cpu
epochs:
    value: 100
expansion_factor:
    value: 8
l1:
    value: 0.0001
lr:
    value: 0.001
